# 빈칸일 시 메시지를 출력하지 않습니다.
message:
  prevented-item: "§c조합이 금지된 아이템입니다."

prevent-crafting:
  예시:
    # MATERIAL, MATERIAL_CONTAIN, LEGACY
    # ex) type에 MATERIAL_CONTAIN을 적고
    #     material에 PICKAXE를 적을 시 PICKAXE가 포함된 아이템이면 모두 금지됩니다.
    # ex) LEGACY는 1.12.2 이하에서 사용하시면 됩니다.
    type: MATERIAL
    # 아이템 - type이 LEGACY일 시 아이템 코드로 인식합니다.
    material: WOODEN_PICKAXE
    # 내구도 - type이 LEGACY일 시 적용됩니다.
    # -1을 적을 시 모든 내구도에 조합 금지가 적용됩니다.
    durability: 0
  레거시-예시:
    type: LEGACY
    material: 270
    durability: 0